---
title: "Untitled"
author: "Aabha Latkar & Amie Thomas"
date: "2024-04-04"
output: html_document
---


###Data Cleaning and EDA
```{r}
#needed libraries
library(readr)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(stats)
library(haven)
library(ggfortify)
library(cluster)
```

```{r}
#load in the data
sessions <- read_csv("log_mini.csv", show_col_types = FALSE)
features_data <- read_csv("tf_mini.csv", show_col_types = FALSE)
```

```{r}
#get rid of sessions that are not random to meet conditional exchangeability
sessions <- sessions |>
  filter(hist_user_behavior_is_shuffle == TRUE)

#Get rid of rows where song was skipped because the session ended
sessions <- sessions |>
  filter(hist_user_behavior_reason_end != "logout")

# make binary. 0 for not skipped 1 for skipped
sessions$not_skipped <- ifelse(sessions$not_skipped == TRUE, 0, 1)

#get rid of columns not needed for analysis
sessions <- select(sessions, -session_length, -skip_2, -skip_1, -skip_3, -short_pause_before_play, -long_pause_before_play, -hour_of_day, -date, -hist_user_behavior_reason_start,-hist_user_behavior_reason_end, -hist_user_behavior_n_seekfwd, -hist_user_behavior_n_seekback, -hist_user_behavior_is_shuffle)

```

```{r}
#get rid of columns 
new_feat <- features_data[ , c(1, 5:22)][ , -c(10, 14, 18)]|>
  select(-10,-13)

numeric_data <- new_feat |>
  select(where(is.numeric))

# Perform feature scaling if needed (optional but recommended for PCA)
scaled_data <- scale(numeric_data)

set.seed(592)

# Perform PCA 
# combines all song features to capture the overall vibe of a song
pca_result <- prcomp(scaled_data, center = TRUE, scale. = TRUE)

# Extract principal components that explain a certain percentage of variance (e.g., 95%)
variance_explained <- cumsum(pca_result$sdev^2) / sum(pca_result$sdev^2)
num_components <- which.max(variance_explained > 0.95)

# Select the first 'num_components' principal components
pc_data <- as.data.frame(predict(pca_result, newdata = scaled_data)[, 1:num_components])

factor_loadings <- pca_result$rotation

```

```{r}
#PCA visuals

#biplot
autoplot(pca_result, data = pca_result, colour = 'black',
         loadings = TRUE, loadings.colour = 'blue',
         loadings.label = TRUE, loadings.label.size = 5)

#heatmap
heatmap(factor_loadings, 
        col = colorRampPalette(c("blue", "white", "red"))(100),  # Color palette
        scale = "none",  # No scaling
        main = "Heatmap of Factor Loadings",  # Title of the plot
        xlab = "Principal Components",  # X-axis label
        ylab = "Features"  # Y-axis label
)

#scree plot
plot(1:length(variance_explained), variance_explained, 
     type = "b", 
     main = "Scree Plot",
     xlab = "Principal Component",
     ylab = "Proportion of Variance Explained"
)

```

```{r}
# Perform clustering 
#clustering finds groups of songs that might have the same combination of song features implying that it is the same vibe or genre

scaled_pc_data <- scale(pc_data)
k <- 10
kmeans_result <- kmeans(scaled_pc_data, centers = k)

# Add cluster assignments to the original dataset
data_with_clusters <- cbind(new_feat, Cluster = kmeans_result$cluster)
```

```{r}
#Clustering visual

#songs that belong to certain clusters
data_with_clusters$Cluster <- factor(data_with_clusters$Cluster)

autoplot(pca_result, data = data_with_clusters, colour = 'Cluster', frame = TRUE) +
  scale_color_manual(values = rainbow(length(unique(data_with_clusters$Cluster))))


#distribution of how many songs are in each cluster
cluster_counts <- table(data_with_clusters$Cluster)


cluster_counts_df <- as.data.frame(cluster_counts)
colnames(cluster_counts_df) <- c("Cluster", "Count")

ggplot(cluster_counts_df, aes(x = Cluster, y = Count, fill = Cluster)) +
  geom_bar(stat = "identity") +
  labs(title = "Count of Songs in Each Cluster", x = "Cluster", y = "Count") +
  scale_fill_brewer(palette = "Set3") +  # Set a color palette
  theme_minimal()

#distribution of the clusters

```

```{r}
danceability <- new_feat$danceability
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(danceability, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = danceability, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Danceability in Clusters",
       x = "Danceability",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  # Use rainbow colors
  facet_wrap(~ Cluster, nrow = 2) +  # Separate histograms by cluster
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Tilt x-axis labels


```

```{r}

acousticness <- new_feat$acousticness
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(acousticness, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = acousticness, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Acoustic in Clusters",
       x = "Acousticness",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

```{r}
beat_strength <- new_feat$beat_strength
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(beat_strength, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = beat_strength, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Beat Strength in Clusters",
       x = "Beat Strength",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

```{r}
bounciness <- new_feat$bounciness
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(bounciness, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = bounciness, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Bounciness in Clusters",
       x = "Bounciness",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

```{r}
dyn_range_mean <- new_feat$dyn_range_mean
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(dyn_range_mean, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = dyn_range_mean, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Dynamic Range in Clusters",
       x = "Dynamic Range",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

```{r}
energy <- new_feat$energy
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(energy, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = energy, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Energy in Clusters",
       x = "Energy",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

```{r}
flatness <- new_feat$flatness
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(flatness, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = flatness, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Flatness in Clusters",
       x = "Flatness",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

```{r}
instrumentalness <- new_feat$instrumentalness
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(instrumentalness, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = instrumentalness, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Instrumentalness in Clusters",
       x = "Instrumentalness",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

```{r}
loudness <- new_feat$loudness
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(loudness, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = loudness, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Loudness in Clusters",
       x = "Loudness",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

```{r}
mechanism <- new_feat$mechanism
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(mechanism, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = mechanism, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Mechanism in Clusters",
       x = "Mechanism",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

```{r}
speechiness <- new_feat$speechiness
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(speechiness, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = speechiness, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Speechiness in Clusters",
       x = "Speechiness",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

```{r}
tempo <- new_feat$tempo
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(tempo, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = tempo, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Tempo in Clusters",
       x = "Tempo",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

```{r}
valence <- new_feat$valence
cluster <- kmeans_result$cluster

data_for_plot <- data.frame(valence, Cluster = factor(cluster))

ggplot(data_for_plot, aes(x = valence, fill = factor(Cluster))) +
  geom_histogram(binwidth = 0.05, position = "identity", alpha = 0.7) +
  labs(title = "Distribution of Valence in Clusters",
       x = "Valence",
       y = "Frequency") +
  scale_fill_manual(values = rainbow(nlevels(factor(cluster)))) +  
  facet_wrap(~ Cluster, nrow = 2) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

```{r}
sessions <- sessions |>
  rename(track_id = track_id_clean)

#join sessions dataset with feature clusters to create one dataset
joined_dataset <- left_join(sessions, data_with_clusters, by = "track_id")

final <- subset(joined_dataset, select = c("session_id", "session_position", "track_id", "not_skipped", "context_switch", "no_pause_before_play", "premium", "context_type", "Cluster"))

```

```{r}
#merge datasets
cluster_similarity <- rep(0, nrow(final))
 
change_indices <- unlist(tapply(final$Cluster, final$session_id, 
                                function(x) c(TRUE, diff(x) != 0)))
 
cluster_similarity[change_indices] <- 1
cluster_similarity[is.na(cluster_similarity)] <- 0 
 
# Find the indices of the first row for each session ID
first_row_indices <- tapply(seq_along(final$session_id), final$session_id, head, 1)
 
# Set the first row of each session ID to NA
cluster_similarity[first_row_indices] <- NA
 
final$cluster_similarity <- cluster_similarity

```


###Begin Analysis
```{r}
 # Fit regression models
    fit <- glm(not_skipped ~ . -not_skipped, data = final, family= "binomial")
    

```